##########################################################################
# Title:         Sandbox: Profilarr-V2 | Default Variables               #
# Author(s):     notlimahrelyt                                           #
# URL:           https://github.com/saltyorg/Sandbox                     #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

profilarr_v2_name: profilarr-v2

################################
# Paths
################################

profilarr_v2_role_paths_folder: "{{ profilarr_v2_name }}"
profilarr_v2_role_paths_location: "{{ server_appdata_path }}/{{ profilarr_v2_role_paths_folder }}"
profilarr_v2_role_paths_folders_list:
  - "{{ profilarr_v2_role_paths_location }}"

################################
# Web
################################

profilarr_v2_role_web_subdomain: "{{ profilarr_v2_name }}"
profilarr_v2_role_web_domain: "{{ user.domain }}"
profilarr_v2_role_web_port: "6868"
profilarr_v2_role_web_url: "{{ 'https://' + (lookup('role_var', '_web_subdomain', role='profilarr_v2') + '.' + lookup('role_var', '_web_domain', role='profilarr_v2')
                         if (lookup('role_var', '_web_subdomain', role='profilarr_v2') | length > 0)
                         else lookup('role_var', '_web_domain', role='profilarr_v2')) }}"

################################
# DNS
################################

profilarr_v2_role_dns_record: "{{ lookup('role_var', '_web_subdomain', role='profilarr_v2') }}"
profilarr_v2_role_dns_zone: "{{ lookup('role_var', '_web_domain', role='profilarr_v2') }}"
profilarr_v2_role_dns_proxy: "{{ dns_proxied }}"

################################
# Traefik
################################

profilarr_v2_role_traefik_sso_middleware: "{{ traefik_default_sso_middleware }}"
profilarr_v2_role_traefik_middleware_default: "{{ traefik_default_middleware }}"
profilarr_v2_role_traefik_middleware_custom: ""
profilarr_v2_role_traefik_certresolver: "{{ traefik_default_certresolver }}"
profilarr_v2_role_traefik_enabled: true
profilarr_v2_role_traefik_api_enabled: true
profilarr_v2_role_traefik_api_endpoint: "PathPrefix(`/api`)"

################################
# Docker
################################

# Container
profilarr_v2_role_docker_container: "{{ profilarr_v2_name }}"

# Image
profilarr_v2_role_docker_image_pull: true
profilarr_v2_role_docker_image_repo: "ghcr.io/dictionarry-hub/profilarr"
profilarr_v2_role_docker_image_tag: "latest"
profilarr_v2_role_docker_image: "{{ lookup('role_var', '_docker_image_repo', role='profilarr_v2') }}:{{ lookup('role_var', '_docker_image_tag', role='profilarr_v2') }}"

# Envs
profilarr_v2_role_docker_envs_default:
  PUID: "{{ uid }}"
  PGID: "{{ gid }}"
  TZ: "{{ tz }}"
  ORIGIN: "{{ profilarr_v2_role_web_url }}"
profilarr_v2_role_docker_envs_custom: {}
profilarr_v2_role_docker_envs: "{{ lookup('role_var', '_docker_envs_default', role='profilarr_v2')
                                | combine(lookup('role_var', '_docker_envs_custom', role='profilarr_v2')) }}"

# Volumes
profilarr_v2_role_docker_volumes_default:
  - "{{ profilarr_v2_role_paths_location }}:/config"
profilarr_v2_role_docker_volumes_custom: []
profilarr_v2_role_docker_volumes: "{{ lookup('role_var', '_docker_volumes_default', role='profilarr_v2')
                                   + lookup('role_var', '_docker_volumes_custom', role='profilarr_v2') }}"

# Hostname
profilarr_v2_role_docker_hostname: "{{ profilarr_v2_name }}"

# Networks
profilarr_v2_role_docker_networks_alias: "{{ profilarr_v2_name }}"
profilarr_v2_role_docker_networks_default: []
profilarr_v2_role_docker_networks_custom: []
profilarr_v2_role_docker_networks: "{{ docker_networks_common
                                    + lookup('role_var', '_docker_networks_default', role='profilarr_v2')
                                    + lookup('role_var', '_docker_networks_custom', role='profilarr_v2') }}"

# Restart Policy
profilarr_v2_role_docker_restart_policy: unless-stopped

# State
profilarr_v2_role_docker_state: started
