#########################################################################
# Title:         Sandbox: Sanity Check                                  #
# Author(s):     desimaniac, salty                                      #
# URL:           https://github.com/saltyorg/Sandbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Saltbox Check"
  ansible.builtin.import_tasks: "subtasks/saltbox_check.yml"
  tags: always

- name: "Ansible Check"
  ansible.builtin.import_tasks: "subtasks/ansible_check.yml"
  tags: always

- name: "Backup Check"
  ansible.builtin.import_tasks: "subtasks/backup_check.yml"
  tags: always

- name: "Repo Check"
  ansible.builtin.import_tasks: "subtasks/repo.yml"
  tags: always

- name: "Cloudflare Zone Check"
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/cloudflare/resolve_certificate_zones.yml"
  when:
    - traefik_challenge_provider == 'cloudflare'
    - cloudflare_is_enabled
    - not traefik_http
  tags: always
