#########################################################################
# Title:         Sandbox: Sanity Check                                  #
# Author(s):     desimaniac, salty                                      #
# URL:           https://github.com/saltyorg/Sandbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Saltbox Check"
  ansible.builtin.include_tasks:
    file: "subtasks/saltbox_check.yml"
    apply:
      tags:
        - always
  tags: always

- name: "Ansible Check"
  ansible.builtin.include_tasks:
    file: "subtasks/ansible_check.yml"
    apply:
      tags:
        - always
  tags: always

- name: "Backup Check"
  ansible.builtin.include_tasks:
    file: "subtasks/backup_check.yml"
    apply:
      tags:
        - always
  tags: always

- name: "Repo Check"
  ansible.builtin.include_tasks:
    file: "subtasks/repo.yml"
    apply:
      tags:
        - always
  tags: always
