##########################################################################
# Title:            Sandbox: tofa                                        #
# Author(s):        gylli251                                             #
# URL:              https://github.com/saltyorg/Sandbox                  #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
- name: Add DNS record
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/dns/tasker.yml"
  vars:
    dns_record: "{{ lookup('role_var', '_dns_record') }}"
    dns_zone: "{{ lookup('role_var', '_dns_zone') }}"
    dns_proxy: "{{ lookup('role_var', '_dns_proxy') }}"

- name: Remove existing Docker container
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/remove_docker_container.yml"

- name: Initialize or update port range low bound
  ansible.builtin.set_fact:
    tofa_port_range_low_bound: "{{ tofa_port_range_low_bound | default(33333) }}"
  when: lookup('role_var', '_open_main_ports', role='tofa')

- name: Get next available port within the range of '33333-33433'
  find_open_port:
    low_bound: "{{ tofa_port_range_low_bound }}"
    high_bound: 33433
    protocol: tcp
  register: port_lookup_33333
  ignore_errors: true
  when: lookup('role_var', '_open_main_ports', role='tofa')

- name: Update port range low bound for next iteration
  ansible.builtin.set_fact:
    tofa_port_range_low_bound: "{{ (lookup('role_var', '_docker_ports_33333', role='tofa') | int) + 1 }}"
  when: lookup('role_var', '_open_main_ports', role='tofa')

- name: Create directories
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/directories/create_directories.yml"

- name: Create Docker container
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/create_docker_container.yml"
