#######################################################################
# Title:         Sandbox: PlexTraktSync | Tasks                       #
# Author(s):     keldian                                              #
# URL:           https://github.com/saltyorg/Sandbox                  #
# --                                                                  #
#######################################################################
#                   GNU General Public License v3.0                   #
#######################################################################
---
- name: "Execute PlexTraktSync roles"
  ansible.builtin.include_tasks: main2.yml
  vars:
    plextraktsync_name: "{{ instance }}"
  with_items: "{{ plextraktsync_instances }}"
  loop_control:
    loop_var: instance
