######################################################################################
# Title:         Sandbox: Transmission | Post-Install | Settings | Existing Installs #
# Author(s):     salty                                                               #
# URL:           https://github.com/saltyorg/Sandbox                                 #
# --                                                                                 #
######################################################################################
#                   GNU General Public License v3.0                                  #
######################################################################################
---
- name: Post-Install | Settings | Update 'settings.json' config settings
  block:
    - name: Post-Install | Settings | Read settings.json
      ansible.builtin.slurp:
        src: "{{ lookup('role_var', '_paths_setttings_location', role='transmission') }}"
      register: transmission_settings_content
      no_log: true

    - name: Post-Install | Settings | Parse settings.json
      ansible.builtin.set_fact:
        transmission_settings_data: "{{ transmission_settings_content.content | b64decode | from_json }}"
      no_log: true

    - name: Post-Install | Settings | Update peer port
      ansible.builtin.set_fact:
        transmission_settings_updated: "{{ transmission_settings_data
                                           | combine({'peer-port': transmission_port_assignment.ports.peer | int}) }}"
      no_log: true

    - name: Post-Install | Settings | Write settings.json
      ansible.builtin.copy:
        content: "{{ transmission_settings_updated | to_nice_json(indent=2) }}\n"
        dest: "{{ lookup('role_var', '_paths_setttings_location', role='transmission') }}"
        owner: "{{ user.name }}"
        group: "{{ user.name }}"
        mode: "0664"
      no_log: true

- name: Post-Install | Settings | Set '{{ lookup('role_var', '_paths_location', role='transmission') }}' ownership recursively
  ansible.builtin.file:
    path: "{{ lookup('role_var', '_paths_location', role='transmission') }}"
    state: directory
    recurse: true
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
